# Generated by Django 2.1.8 on 2019-05-14 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster2_url',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
